// Centralized bank of quotes (Scripture + theologians), ported from the Android QuoteBank.
const QUOTES = [
  { label: "Word for Today", text: "For the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and of spirit, of joints and of marrow, and discerning the thoughts and intentions of the heart.", attribution: "Hebrews 4:12" },
  { label: "Word for Today", text: "God is our refuge and strength, a very present help in trouble.", attribution: "Psalm 46:1" },
  { label: "Word for Today", text: "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.", attribution: "Isaiah 41:10" },
  { label: "Word for Today", text: "The steadfast love of the LORD never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.", attribution: "Lamentations 3:22–23" },
  { label: "Word for Today", text: "Trust in the LORD with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.", attribution: "Proverbs 3:5–6" },
  { label: "Word for Today", text: "My grace is sufficient for you, for my power is made perfect in weakness.", attribution: "2 Corinthians 12:9" },
  { label: "Word for Today", text: "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.", attribution: "Philippians 4:6" },
  { label: "Word for Today", text: "If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.", attribution: "1 John 1:9" },
  { label: "Word for Today", text: "Come to me, all who labor and are heavy laden, and I will give you rest.", attribution: "Matthew 11:28" },
  { label: "Word for Today", text: "He heals the brokenhearted and binds up their wounds.", attribution: "Psalm 147:3" },
  { label: "Word for Today", text: "For I am sure that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers, nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord.", attribution: "Romans 8:38–39" },
  { label: "Spurgeon", text: "I have learned to kiss the wave that throws me against the Rock of Ages.", attribution: "C.H. Spurgeon" },
  { label: "Spurgeon", text: "No man can do me a truer kindness in this world than to pray for me.", attribution: "C.H. Spurgeon" },
  { label: "Spurgeon", text: "It is not how much we have, but how much we enjoy, that makes happiness.", attribution: "C.H. Spurgeon" },
  { label: "Spurgeon", text: "The cross of Christ is the lever which has lifted the world.", attribution: "C.H. Spurgeon" },
  { label: "Spurgeon", text: "When you cannot trace God's hand, you can trust God's heart.", attribution: "C.H. Spurgeon" },
  { label: "Spurgeon", text: "By perseverance the snail reached the ark.", attribution: "C.H. Spurgeon" },
  { label: "Jonathan Edwards", text: "The enjoyment of God is the only happiness with which our souls can be satisfied.", attribution: "Jonathan Edwards" },
  { label: "Jonathan Edwards", text: "Resolution One: I will live for God. Resolution Two: If no one else does, I still will.", attribution: "Jonathan Edwards" },
  { label: "Jonathan Edwards", text: "Prayer is as natural an expression of faith as breathing is of life.", attribution: "Jonathan Edwards" },
  { label: "Jonathan Edwards", text: "The chief end of God in creation is to communicate Himself, and not to receive anything from the creature.", attribution: "Jonathan Edwards" },
  { label: "Jonathan Edwards", text: "True religion, in great part, consists in holy affections.", attribution: "Jonathan Edwards" },
  { label: "John Owen", text: "Be killing sin, or sin will be killing you.", attribution: "John Owen" },
  { label: "John Owen", text: "A man may easier see without eyes, hear without ears, and live without life, than truly repent without the special operation of the Holy Spirit.", attribution: "John Owen" },
  { label: "John Owen", text: "Let not conscience be afraid to deal with sin as sin, whatever names or pleas it puts on.", attribution: "John Owen" },
  { label: "John Owen", text: "He who finds it easy to repent, may find it difficult to believe.", attribution: "John Owen" },
  { label: "John Owen", text: "The choicest believers are exercised with abundance of perplexities about their interest in the love of God.", attribution: "John Owen" },
  { label: "R.C. Sproul", text: "The Christian life is not a playground; it is a battleground.", attribution: "R.C. Sproul" },
  { label: "R.C. Sproul", text: "God does not need us. We need God. And that is the beginning of wisdom.", attribution: "R.C. Sproul" },
  { label: "R.C. Sproul", text: "If there's even one maverick molecule running around the universe outside of God's sovereign control, then we have no guarantee that a single promise of God will ever be fulfilled.", attribution: "R.C. Sproul" },
  { label: "R.C. Sproul", text: "We are fallen creatures who, by nature, are inclined to godlessness.", attribution: "R.C. Sproul" },
  { label: "R.C. Sproul", text: "The most important thing that has ever happened to me, and the most important thing that ever will happen to me, is that I have been adopted into the family of God.", attribution: "R.C. Sproul" },
  { label: "John Piper", text: "God is most glorified in us when we are most satisfied in Him.", attribution: "John Piper" },
  { label: "John Piper", text: "The greatest enemy of hunger for God is not poison but apple pie.", attribution: "John Piper" },
  { label: "John Piper", text: "Christian Hedonism does not say that the pursuit of happiness is wrong, but that we have settled for too little.", attribution: "John Piper" },
  { label: "John Piper", text: "Don't waste your life.", attribution: "John Piper" },
  { label: "John Piper", text: "The world is not impressed when the church is rich. The world is not impressed when Christians own their own jets and drive luxury cars.", attribution: "John Piper" },
  { label: "Paul Washer", text: "You are not the product of your past. You are the product of the grace of God.", attribution: "Paul Washer" },
  { label: "Paul Washer", text: "The mark of a man who is truly converted is that he is never done with repentance.", attribution: "Paul Washer" },
  { label: "Paul Washer", text: "The greatest news of the gospel is not that God has a wonderful plan for your life, but that God has a wonderful plan to redeem sinners.", attribution: "Paul Washer" },
  { label: "Paul Washer", text: "We've taken the Sermon on the Mount and made it the Sermon on the Couch.", attribution: "Paul Washer" },
  { label: "Paul Washer", text: "If you're not willing to suffer for Christ, then you're really not willing to live for Christ.", attribution: "Paul Washer" },
  { label: "Thomas Watson", text: "Repentance is a grace of God's Spirit whereby a sinner is inwardly humbled and visibly reformed.", attribution: "Thomas Watson" },
  { label: "Thomas Watson", text: "The Spirit of God is a comforter; but he cannot comfort those who are not afflicted.", attribution: "Thomas Watson" },
  { label: "Thomas Watson", text: "A man may go to heaven without health, without riches, without honors; but he can never go there without Christ.", attribution: "Thomas Watson" },
  { label: "Thomas Watson", text: "All the troubles and miseries that befall us are for the sins we commit against God.", attribution: "Thomas Watson" },
  { label: "Thomas Watson", text: "Sorrow for sin is in order to the small joy which the soul has in God.", attribution: "Thomas Watson" },
  { label: "Thomas Watson", text: "Faith is the mother and root of patience.", attribution: "Thomas Watson" },
  { label: "Richard Sibbes", text: "There is more mercy in Christ than sin in us.", attribution: "Richard Sibbes" },
  { label: "Richard Sibbes", text: "God's children are never so safe and secure as when they are most sensible of their own weakness.", attribution: "Richard Sibbes" },
  { label: "Richard Sibbes", text: "Where Christ is a foundation, He is laid for our peace.", attribution: "Richard Sibbes" },
  { label: "Richard Sibbes", text: "The greatest part of a Christian's grace lies in mourning for his infirmities.", attribution: "Richard Sibbes" },
  { label: "Richard Sibbes", text: "Comfort from God always carries with it suitableness to our present condition.", attribution: "Richard Sibbes" },
  { label: "Psalm 139:23–24", text: "Search me, O God, and know my heart! Try me and know my thoughts! And see if there be any grievous way in me, and lead me in the way everlasting.", attribution: "Psalm 139:23–24" },
  { label: "Psalm 51:10", text: "Create in me a clean heart, O God, and renew a right spirit within me.", attribution: "Psalm 51:10" },
  { label: "2 Corinthians 7:10", text: "For godly grief produces a repentance that leads to salvation without regret, whereas worldly grief produces death.", attribution: "2 Corinthians 7:10" },
  { label: "Jeremiah 17:9", text: "The heart is deceitful above all things, and desperately sick; who can understand it?", attribution: "Jeremiah 17:9" },
  { label: "Proverbs 4:23", text: "Keep your heart with all vigilance, for from it flow the springs of life.", attribution: "Proverbs 4:23" },
  { label: "Galatians 2:20", text: "I have been crucified with Christ. It is no longer I who live, but Christ who lives in me. And the life I now live in the flesh I live by faith in the Son of God, who loved me and gave himself for me.", attribution: "Galatians 2:20" },
  { label: "1 Corinthians 10:13", text: "No temptation has overtaken you that is not common to man. God is faithful, and he will not let you be tempted beyond your ability, but with the temptation he will also provide the way of escape.", attribution: "1 Corinthians 10:13" },
  { label: "Romans 8:28", text: "And we know that for those who love God all things work together for good, for those who are called according to his purpose.", attribution: "Romans 8:28" },
  { label: "Matthew 5:8", text: "Blessed are the pure in heart, for they shall see God.", attribution: "Matthew 5:8" },
  { label: "Hebrews 12:1", text: "Therefore, since we are surrounded by so great a cloud of witnesses, let us also lay aside every weight, and sin which clings so closely, and let us run with endurance the race that is set before us.", attribution: "Hebrews 12:1" },
  { label: "Martin Luther", text: "To progress is always to begin again.", attribution: "Martin Luther" },
  { label: "John Calvin", text: "There is not one blade of grass, there is no color in this world that is not intended to make us rejoice.", attribution: "John Calvin" },
  { label: "J.C. Ryle", text: "Beware of manufacturing a God of your own: a God who is all mercy but not just, a God who is all love but not holy, a God who has a heaven for everybody but a hell for none.", attribution: "J.C. Ryle" },
  { label: "Martyn Lloyd-Jones", text: "Have you realized that most of your unhappiness in life is due to the fact that you are listening to yourself instead of talking to yourself?", attribution: "Martyn Lloyd-Jones" },
  { label: "Martyn Lloyd-Jones", text: "The glory of the gospel is that when the Church is absolutely different from the world, she invariably attracts it.", attribution: "Martyn Lloyd-Jones" },
  { label: "Samuel Rutherford", text: "Whenever I find myself in the cellar of affliction, I look about for the wine.", attribution: "Samuel Rutherford" },
  { label: "Samuel Rutherford", text: "Grace tried is better than grace, and more than grace; it is glory in its infancy.", attribution: "Samuel Rutherford" },
  { label: "Augustine", text: "Thou hast made us for thyself, O Lord, and our heart is restless until it finds its rest in thee.", attribution: "Augustine" },
  { label: "Augustine", text: "Love God, and do whatever you please: for the soul trained in love to God will do nothing to offend the One who is Beloved.", attribution: "Augustine" },
  { label: "John MacArthur", text: "Discernment is not a matter of simply telling the difference between right and wrong; rather it is telling the difference between right and almost right.", attribution: "John MacArthur" },
  { label: "John MacArthur", text: "The purpose of the Christian life is not self-fulfillment but self-denial.", attribution: "John MacArthur" },
  { label: "George Whitefield", text: "Take care of your life; and the Lord will take care of your death.", attribution: "George Whitefield" },
  { label: "George Whitefield", text: "It is a poor sermon that gives no offense; that neither makes the hearer displeased with himself nor with the preacher.", attribution: "George Whitefield" },
  { label: "Matthew Henry", text: "It ought to be the business of every day to prepare for our last day.", attribution: "Matthew Henry" },
  { label: "A.W. Pink", text: "The sovereignty of God is the pillow upon which the child of God rests his head at night, giving perfect peace.", attribution: "A.W. Pink" },
  { label: "John Newton", text: "I am not what I ought to be, I am not what I want to be, I am not what I hope to be. But still, I am not what I used to be, and by the grace of God, I am what I am.", attribution: "John Newton" },
  { label: "John Newton", text: "Many have puzzled themselves about the origin of evil. I am content to observe that there is evil, and that there is a way to escape from it.", attribution: "John Newton" },
  { label: "C.H. Spurgeon", text: "You will never find Jesus so precious as when the world is one vast howling wilderness. Then He is like a rose blooming in the midst of the desolation.", attribution: "C.H. Spurgeon" },
  { label: "J.C. Ryle", text: "A man's state before God is not what he appears to be to others, or even to himself. It is what he is in the sight of God.", attribution: "J.C. Ryle" },
  { label: "Martin Luther", text: "Here I stand. I can do no other.", attribution: "Martin Luther" },
  { label: "Martin Luther", text: "Faith is a living, daring confidence in God's grace.", attribution: "Martin Luther" },
  { label: "Martin Luther", text: "A religion that gives nothing, costs nothing, and suffers nothing, is worth nothing.", attribution: "Martin Luther" },
  { label: "John Calvin", text: "All the gifts which we possess have been bestowed by God, and that for the very purpose of being employed in his service.", attribution: "John Calvin" },
  { label: "John Calvin", text: "Man's nature, so to speak, is a perpetual factory of idols.", attribution: "John Calvin" },
  { label: "John Calvin", text: "True and substantial wisdom principally consists of two parts: the knowledge of God and of ourselves.", attribution: "John Calvin" },
  { label: "J.C. Ryle", text: "We must not measure the truth of God's word by the feelings of our hearts.", attribution: "J.C. Ryle" },
  { label: "J.C. Ryle", text: "He that wishes to be a true Christian must do nothing by halves.", attribution: "J.C. Ryle" },
  { label: "J.C. Ryle", text: "Reader, are you born again? You may know it by the fruit you bear.", attribution: "J.C. Ryle" },
  { label: "Martyn Lloyd-Jones", text: "We are never told to feed our doubts and fears. We are called to feed our faith.", attribution: "Martyn Lloyd-Jones" },
  { label: "Martyn Lloyd-Jones", text: "The essence of sin is independence; the essence of salvation is dependence.", attribution: "Martyn Lloyd-Jones" },
  { label: "Martyn Lloyd-Jones", text: "Faith, in a sense, can be defined as the refusal to panic.", attribution: "Martyn Lloyd-Jones" },
  { label: "Samuel Rutherford", text: "Down, down, proud thoughts, and let Christ's love triumph and ride upon the necks of all your imaginations.", attribution: "Samuel Rutherford" },
  { label: "Samuel Rutherford", text: "I find it most true that the greatest temptations are not on the top of high mountains, but rather in low and pleasant valleys.", attribution: "Samuel Rutherford" },
  { label: "Samuel Rutherford", text: "Build your nest in no tree here, for God hath sold the forest to death.", attribution: "Samuel Rutherford" },
  { label: "Augustine", text: "Faith is to believe what we do not see; and the reward of this faith is to see what we believe.", attribution: "Augustine" },
  { label: "Augustine", text: "Late have I loved you, O Beauty ever ancient, ever new.", attribution: "Augustine" },
  { label: "Augustine", text: "Patience is the companion of wisdom.", attribution: "Augustine" },
  { label: "John MacArthur", text: "The Bible is not a book to be studied only; it is a book to be obeyed.", attribution: "John MacArthur" },
  { label: "John MacArthur", text: "True love for God always demonstrates itself in obedience.", attribution: "John MacArthur" },
  { label: "John MacArthur", text: "Sound doctrine is the foundation for godly living.", attribution: "John MacArthur" },
  { label: "George Whitefield", text: "I would rather wear out than rust out.", attribution: "George Whitefield" },
  { label: "George Whitefield", text: "Let the name of Whitefield perish, but Christ be glorified.", attribution: "George Whitefield" },
  { label: "George Whitefield", text: "We are all by nature enemies to God.", attribution: "George Whitefield" },
  { label: "Matthew Henry", text: "Those that truly repent of their sin truly hate it.", attribution: "Matthew Henry" },
  { label: "Matthew Henry", text: "What we win by prayer we wear with comfort.", attribution: "Matthew Henry" },
  { label: "Matthew Henry", text: "Sin is the work of darkness; holiness is the work of God.", attribution: "Matthew Henry" },
  { label: "A.W. Pink", text: "Faith is not a sense of pardon, nor a feeling that Christ is mine and I am His.", attribution: "A.W. Pink" },
  { label: "A.W. Pink", text: "The lower our estimate of self, the higher will be our esteem for Christ.", attribution: "A.W. Pink" },
  { label: "A.W. Pink", text: "Real faith is shown by our works, just as health is demonstrated by our pulse.", attribution: "A.W. Pink" },
  { label: "John Newton", text: "If two angels came down from heaven to fulfill a divine command, and one was assigned to be a king and the other a street sweeper, they would feel no inclination to change places.", attribution: "John Newton" },
  { label: "John Newton", text: "Satan is a great picklock, the most cunning and most experienced thief in the world.", attribution: "John Newton" },
  { label: "John Newton", text: "I am a great sinner, and Christ is a great Savior.", attribution: "John Newton" },
  { label: "Joshua 1:9", text: "Have I not commanded you? Be strong and courageous. Do not be frightened, and do not be dismayed, for the LORD your God is with you wherever you go.", attribution: "Joshua 1:9" },
  { label: "Psalm 23:1", text: "The LORD is my shepherd; I shall not want.", attribution: "Psalm 23:1" },
  { label: "Romans 5:8", text: "But God shows his love for us in that while we were still sinners, Christ died for us.", attribution: "Romans 5:8" },
  { label: "Ephesians 2:8–9", text: "For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast.", attribution: "Ephesians 2:8–9" },
  { label: "John 3:16", text: "For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.", attribution: "John 3:16" },
  { label: "Psalm 34:18", text: "The LORD is near to the brokenhearted and saves the crushed in spirit.", attribution: "Psalm 34:18" },
  { label: "Isaiah 26:3", text: "You keep him in perfect peace whose mind is stayed on you, because he trusts in you.", attribution: "Isaiah 26:3" },
  { label: "2 Timothy 1:7", text: "For God gave us a spirit not of fear but of power and love and self-control.", attribution: "2 Timothy 1:7" },
  { label: "James 1:2–3", text: "Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness.", attribution: "James 1:2–3" },
  { label: "Revelation 21:4", text: "He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away.", attribution: "Revelation 21:4" }
];

/** A quote that's stable for the whole session (changes each app launch). */
function sessionQuote() {
  const idx = Math.floor(Date.now() / 1000 / 60) % QUOTES.length;
  return QUOTES[idx];
}

/** Returns the quote of the day, stable for the whole calendar day. */
function quoteOfTheDay() {
  const dayOfEpoch = Math.floor(Date.now() / (1000 * 60 * 60 * 24));
  const idx = ((dayOfEpoch % QUOTES.length) + QUOTES.length) % QUOTES.length;
  return QUOTES[idx];
}
